# Generated by Django 3.2.3 on 2021-06-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de especie')),
                ('nombreEspecie', models.CharField(max_length=50, verbose_name='Nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='animal',
            fields=[
                ('numChip', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Numero de chip')),
                ('nombreAnimal', models.CharField(max_length=50, verbose_name='Nombre animal')),
                ('edadAnimal', models.CharField(blank=True, max_length=3, verbose_name='Edad animal')),
                ('generoAnimal', models.CharField(max_length=6, verbose_name='Genero animal')),
                ('esterilizacion', models.BooleanField(verbose_name='Esterilizacion')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especie')),
            ],
        ),
    ]
