# Generated by Django 3.2.3 on 2021-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='edadAnimal',
            field=models.CharField(blank=True, max_length=50, verbose_name='Edad animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='generoAnimal',
            field=models.CharField(max_length=50, verbose_name='Genero animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numChip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Numero de chip'),
        ),
    ]
