# Generated by Django 3.2.3 on 2021-06-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_imagenanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagenAnimal',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
