# Generated by Django 3.2.3 on 2021-06-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_animal_imagenanimal'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='core_Animal',
        ),
    ]
